### ISSUE TITLE
Removed from registry?

### ISSUE THREAD

**Issue by ljrk0** [thought2/purescript-ts-bridge#13]
I just noticed that this package was removed in package set 39, is there any reason why it shouldn't be available anymore?

https://github.com/purescript/registry/commit/14485f9a97fa59ea2699c1b1e5a4b1057b1b61f5

**Comment by thought2** [comment]
Oh, I think this is due to the breaking changes in node related libraries.
I just tried to update to the latest package set (`44.2.0`), but this fails due to the following dependencies being removed, too:

  - node-fs-aff
    _this is no issue, since it's been moved to `node-fs`_
  - optparse
    _created an [issue on their repo](https://github.com/f-o-a-m/purescript-optparse/issues/30)_
  - spec-discovery
    _created an [issue on their repo](https://github.com/purescript-spec/purescript-spec-discovery/issues/33)_

I think until the two libraries upgrade, there's nothing I can do.
