### ISSUE TITLE
Variant encodings and typescript side pattern matching

### ISSUE THREAD

**Issue by jmatsushita** [thought2/purescript-ts-bridge#9]
Hi there,

I'm wondering if you use a particular approach to pattern matching on the typescript side? AFAIA there are a number of ways to do so and I'd like to pick one which has a good chance of being maintained:
 - vanilla `switch` ala https://gcanti.github.io/fp-ts/guides/purescript.html#pattern-matching
 - https://github.com/gvergnaud/ts-pattern
 - https://paarthenon.github.io/variant/docs/intro#match

Do you recommend any approach which would enable compositional pattern matching like in `purescript-variant`, like https://paarthenon.github.io/variant/docs/intro#grouping ?

Cheers,

Jun

**Comment by thought2** [comment]
Generally I'd say the way how pattern matching is done on the typescript side is not so important for this library. The encoding matters though. And via [variant-encodings](https://pursuit.purescript.org/packages/purescript-variant-encodings) I wanted to provide the most common encodings. If you use a library that uses a different encoding and it's common it can be added to `variant-encodings` lib and bindings here.

Depending on what you're doing, another option is to just export an ADT as opaque type and then provide constructors and destructors, something like:

```purs
data Foo = A Int | B String

mkFoo :: {
  _A :: Int -> Foo,
  _B :: String -> Foo
}
mkFoo = ...

matchFoo :: { onA :: Int -> z, onB :: String -> z } -> z
matchFoo = ...
```

With the implementations written manually (for now) and maybe with a generic function in the future. Those functions you can export with ts-bridge right away.


Regarding the compositional matching, that's an interesting point I did not think about yet. For instance we cannot just generate types for variant's [onMatch](https://pursuit.purescript.org/packages/purescript-variant/8.0.0/docs/Data.Variant#v:onMatch) because of the type class constraints. But you can write a TS function that does the same, however expressing the type level code with TS type level code. But this is all on the TS side. And this should work for every kind of encoding.
